<?php

// Email destination. To whom you want the info emailed.
$emailto = "myname@emailme.com";
// Email from field
$emailfrom ="smallstore@emailme.com";
// The subject line
$subject = "order from smallstore";
// The first line that will appear in the email
$firstline = "This order was generated by Smallstore";
?>